version: '3.7'

services:
  # postgis service
  postgis:
    image: postgis/postgis:16-3.4-alpine
    container_name: postgis
    environment:
      POSTGRES_USER: plssmonster
      POSTGRES_PASSWORD: plssmonster
      POSTGRES_DB: plssmonster
    ports:
      - "5432:5432"
    # mount to local directory for db storage
    volumes:
      - ./data_tmp:/var/lib/postgresql/data

  # plssmonster development service
  plssmonster:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: plssmonster
    depends_on:
      - postgis
    environment:
      DATABASE_CS: "host='postgis' user='plssmonster' dbname='plssmonster' password='plssmonster'"
      # DATABASE_URL: "postgresql://plssmonster:plssmonster@postgis:5432/plssmonster"
  

